version: '3.1'

networks:
    net:

services:
    frontend:
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        image: dai-frontend-rcatrangiu:latest
        container_name: frontend
        networks:
            - net
        environment: 
            NODE_ENV: "production"
        ports:
            - 8080:80
        depends_on: 
            - backend
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    backend:
        build: 
            context: ./backend/
            dockerfile: Dockerfile
        image: dai-backend-rcatrangiu:latest
        container_name: backend
        networks:
            - net
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

